"""生成「把现有明文 api_key 加密」的 UPDATE SQL 语句（不直接改库）。

为什么不是纯 SQL：Fernet 密文必须用密钥在 Python 里算，数据库引擎算不出来。
本脚本读取现有明文、算好密文，再以现成 UPDATE 语句输出，你可复制到 DB 客户端执行。

已是密文的行会被跳过（幂等）。默认打印到标准输出，可重定向到文件：
    cd backend
    uv run python scripts/dump_encrypt_sql.py > encrypt_keys.sql

使用的密钥须与运行服务时一致（APP_ENCRYPTION_KEY 或回退的 SECRET_KEY）。
如果只想直接改库而不手动跑 SQL，请改用 scripts/encrypt_existing_keys.py。
"""
from __future__ import annotations

import asyncio
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from sqlalchemy import text  # noqa: E402

from app.core.crypto import _get_fernet, encrypt_str  # noqa: E402
from app.core.database import engine  # noqa: E402

TABLES = ["llms", "image_tools"]


def _is_already_encrypted(value: str) -> bool:
    try:
        _get_fernet().decrypt(value.encode("utf-8"))
        return True
    except Exception:
        return False


def _sql_quote(value: str) -> str:
    # Fernet token 是 urlsafe-base64，不含单引号；仍按标准做转义以防万一。
    return "'" + value.replace("'", "''") + "'"


async def _emit_table(conn, table: str) -> int:
    rows = (await conn.execute(
        text(f"SELECT id, api_key FROM {table}")
    )).all()

    emitted = 0
    lines: list[str] = []
    for row_id, api_key in rows:
        if api_key is None or api_key == "":
            continue
        if _is_already_encrypted(api_key):
            continue
        cipher = encrypt_str(api_key)
        lines.append(f"UPDATE {table} SET api_key = {_sql_quote(cipher)} WHERE id = {row_id};")
        emitted += 1

    if lines:
        print(f"-- {table}: {emitted} row(s) to encrypt")
        print("\n".join(lines))
        print()
    else:
        print(f"-- {table}: nothing to encrypt (all already encrypted / empty)\n")
    return emitted


async def main() -> None:
    print("-- Generated by dump_encrypt_sql.py — review before running.")
    print("-- Run inside a transaction; back up the DB first.\n")
    async with engine.connect() as conn:
        total = 0
        for table in TABLES:
            total += await _emit_table(conn, table)
    await engine.dispose()
    print(f"-- Total statements: {total}", file=sys.stderr)


if __name__ == "__main__":
    asyncio.run(main())
